### ISSUE TITLE
Issue with loop in HAProxy config

### ISSUE THREAD

**Issue by ciphermenial** [crowdsecurity/cs-haproxy-bouncer#13]
[See this discourse post for more information.](https://discourse.crowdsec.net/t/haproxy-bouncer-with-loop-in-haproxy-config/1064/2)

I was trying to figure out how the IPs were detected but had no luck.

**Comment by ciphermenial** [comment]
I am asking in the HAProxy discourse now. forwardfor works to show the correct IP in all my web services so I am guessing I should be able to get it working.

**Comment by ciphermenial** [comment]
This works to detect the correct IP. I replaced ```local source_ip = txn.f:src()``` with:
```lua
    local source_ip;
    
    source_ip = txn.f:req_fhdr("x-forwarded-for");
    if (source_ip == nil) then
        source_ip = txn.f:src()
        if (source_ip == nil) then
            return default;
        end
    end
```
in the crowdsec.lua file.

This detects it correctly but then I have a loop in the captcha. It pops up over and over.

**Comment by LaurenceJJones** [comment]
Hmm guess haproxy does not automatically enforce forwarded headers.... might be best if we configure this in the lua part. Okay, so you get catcha -> solve -> captcha again?

**Comment by ciphermenial** [comment]
My firewall only accepts connections in from CloudFlare.

If I use the normal crowdsec.lua and do a decision based on 127.0.0.1, the captcha works correctly. If I make the change as above it keeps looping after the solve.

**Comment by ciphermenial** [comment]
I have it working now. I changed a line in haproxy.cfg

I changed ```http-request track-sc0 src if { var(req.remediation) -m str "captcha-allow" }``` to ```http-request track-sc0 req.hdr_ip(X-Forwarded-For,-1) if { var(req.remediation) -m str "captcha-allow" }```

**Comment by ciphermenial** [comment]
Thanks for pointing me in the right direction for using CF-Connecting-IP header. I have now fixed up my haproxy config to use that by default.

Would there be a way to add a variable to crowdsec-haproxy-bouncer.conf to detect IP based on a header rather than src?

I believe this would be something a lot of people would find useful.

**Comment by ciphermenial** [comment]
I have created a pull request with what I believe should resolve this issue. #14

**Comment by LaurenceJJones** [comment]
Updating issue with findings:

We don't want to handle trusted headers / trusted IP's via bouncer configuration as it messy, introduces too many vulnerability such as spoofing.

So what we recommend is to use HAproxy in built methods to set the src_ip to the headers you trust from the IP's you trust, an example configuration for cloudflare is
```
  acl from_cf src -f /etc/haproxy/cf-ips/cf-ips
  http-request set-src req.hdr(CF-Connecting-IP) if from_cf
```
`/etc/haproxy/cf-ips/cf-ips` contains a list of cloudflare IP's to which then haproxy will set the src from the header `CF-Connecting-IP` which then the lua code will have the correct IP
