### ISSUE TITLE
Crowdsec logo in README.md shows NGINX logo

### ISSUE THREAD

**Issue by ntimo** [crowdsecurity/cs-haproxy-bouncer#3]
Hello,
I just discovered the project and the first thing I noticed that kind of confused my was that the logo in the readme shows an nginx logo not a HAProxy logo. Is this intentional?

**Comment by LaurenceJJones** [comment]
No it wasnt, we started this project from our nginx project so there was a slight overlap. This is now fixed, thank you for bringing it to our attention as we may have missed it 😄
