### ISSUE TITLE
TLS  Haproxy

### ISSUE THREAD

**Issue by sarjanaBingung** [crowdsecurity/cs-haproxy-bouncer#34]
i getting error for implement connection over TLS, I change this
`    local link = "https://" .. core.backends["crowdsec"].servers["crowdsec"]:get_addr() .. "/v1/decisions/stream?scopes=ip,ipAndId,userId,ipAndPhone,phone&startup=" .. tostring(is_startup)
` to https 

i getting error `Got error fetching decisions from Crowdsec: 503`

**Comment by LaurenceJJones** [comment]
> i getting error for implement connection over TLS, I change this ` local link = "https://" .. core.backends["crowdsec"].servers["crowdsec"]:get_addr() .. "/v1/decisions/stream?scopes=ip,ipAndId,userId,ipAndPhone,phone&startup=" .. tostring(is_startup)` to https
> 
> i getting error `Got error fetching decisions from Crowdsec: 503`

As stated via discord, https is not support at the moment

**Comment by LaurenceJJones** [comment]
Duplicated of #27

**Comment by LaurenceJJones** [comment]
Also to give you a pointer you changed the lua code to `https`, however, the route configuration you put in HAProxy is still http

```
backend crowdsec
 server crowdsec 127.0.0.1:8080 ssl check
```

However, like I said numerous times this is not a supported configuration and will cause issues that you will have to solve yourself
