### ISSUE TITLE
CRowdsec haproxy has error that prevents it from pulling decisions

### ISSUE THREAD

**Issue by geek2gether** [crowdsecurity/cs-haproxy-bouncer#35]
### What happened?

Error after setup:

error: /usr/lib/crowdsec/lua/haproxy/crowdsec.lua:199: attempt to call a nil value (field 'httpclient') from /usr/lib/crowdsec/lua/haproxy/crowdsec.lua:199: in upvalue 'refresh_decisions', /usr/lib/crowdsec/lua/haproxy/crowdsec.lua:271: in function line 260.

[30/Jun/2024:20:28:04.631] <HTTPCLIENT> -/- 2/0/0/15/15 200 153 - - ---- 6/0/0/0/0 0/0 {} "GET http://10.100.20.25:8080/v1/decisions/stream?startup=false HTTP/1.1"
Jun 30 20:28:04 tltsysproxy haproxy[6149]: Decisions fetched: startup=false

### What did you expect to happen?

For ban decisions to load

### How can we reproduce it (as minimally and precisely as possible)?

setup the crowdsec haproxy bouncer

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Thank you for your report, to ensure this get handled on the appropriate repository I will transfer to the HAProxy repo

**Comment by BCreativeS** [comment]
Not sure if this issue has been resolved.  But I'm getting a similar error in my haproxy setup:
 Lua task: [state-id 0] runtime error: /usr/lib/crowdsec/lua/haproxy/crowdsec.lua:199: attempt to call a nil value (field 'httpclient') from /usr/lib/crowdsec/lua/haproxy/crowdsec.lua:199: in upvalue 'refresh_decisions', /usr/lib/crowdsec/lua/haproxy/crowdsec.lua:271: in function line 260.

**Comment by LaurenceJJones** [comment]
Could you post your haproxy versions?

**Comment by BCreativeS** [comment]
Haproxy version: 2.4.24 on Ubuntu 22.04

**Comment by LaurenceJJones** [comment]
> 2.4.24 on Ubuntu 22.04

This remediation only support version `2.5` and upwards https://docs.crowdsec.net/u/bouncers/haproxy

**Comment by LaurenceJJones** [comment]
Classing issue as stale, please reopen when you have more information and confirmed you are a supported version
