### ISSUE TITLE
Support - 90% done integrating cs-haproxy-bouncer with OPNSense

### ISSUE THREAD

**Issue by cookiemonsteruk** [crowdsecurity/cs-haproxy-bouncer#37]
Hello. I am asking here because the opnsense repo has been archived. No answer either on Discord.

Since there is no haproxy bouncer for freebsd, I thought to try using the only one on opnsense to see how far I go.
So I created an acquis ../crowdsec/acquis.d/haproxy.yaml pointing to the haproxy logs. Then downloaded with cscli the haproxy collection. Restarted crowdsec . Now I have a bunch of elements from it: parser, scenarios, collections. Log of crowdsec (agent I think) shows the haproxy logs being added like "time="2024-10-16T15:59:55+01:00" level=info msg="Adding file /var/log/haproxy/haproxy_20241008.log to datasources" type=file".
- Then I downloaded to the firewall the tar for the ha-proxy-bouncer and made the relevant changes to be able to install it on a freeBSD filesystem. 
- - Following https://doc.crowdsec.net/u/bouncers/haproxy/ and https://www.crowdsec.net/blog/the-haproxy-bouncer-is-out
- Registered the remediation manually and completed its config file. 
- Added the haproxy modifications via the additional options that the OPN UI for haproxy add-on provides.
- Created backed and backend servers.
- Created a profile for remediation.
- Signed up to cloudflare turnstile to get a site key and secret key
All seems good. until testing creates a loop on the turnstile. Testing from a client on a different network hitting the WAN. 
I can see the captcha landing page, a tick and success on it powered by cloudflare but just loops, starting and getting to the end before starting again.
My haproxy log shows:
```
2024-10-21T17:38:47	Error	haproxy	Lua function 'crowdsec_allow': [state-id 0] runtime error: /usr/local/lib/crowdsec/lua/haproxy/crowdsec.lua:178: attempt to index a nil value (field 'captcha_verifier') from /usr/local/lib/crowdsec/lua/haproxy/crowdsec.lua:178: in function line 122.	
2024-10-21T17:38:47	Alert	haproxy	error verifying captcha: 503,<html><body><h1>503 Service Unavailable</h1>.No server is available to handle this request..</body></html>.; verifier: {redacted ip address}
```
My crowdsec-haproxy-bouncer.conf:
```
ENABLED=true
API_KEY={redacted}
# haproxy
# path to community_blocklist.map
MAP_PATH=/var/lib/crowdsec/lua/haproxy/community_blocklist.map
# bounce for all type of remediation that the bouncer can receive from the local API
BOUNCING_ON_TYPE=all
FALLBACK_REMEDIATION=ban
REQUEST_TIMEOUT=3000
UPDATE_FREQUENCY=10
# live or stream
MODE=stream
# exclude the bouncing on those location
EXCLUDE_LOCATION=
#those apply for "ban" action
# /!\ REDIRECT_LOCATION and RET_CODE can't be used together. REDIRECT_LOCATION take priority over RET_CODE
# path to ban template
BAN_TEMPLATE_PATH=/var/lib/crowdsec/lua/haproxy/templates/ban.html
REDIRECT_LOCATION=
RET_CODE=
#those apply for "captcha" action
# Captcha Secret Key
SECRET_KEY={redacted}
# captcha Site key
SITE_KEY={redacted}
# path to captcha template
CAPTCHA_TEMPLATE_PATH=/var/lib/crowdsec/lua/haproxy/templates/captcha.html
CAPTCHA_EXPIRATION=3600

```
In haproxy I have a real server called crowdsec pointing to the local LAPI on this server (OPNSense).
I have a backend pool called crowdsec pointing to this server.

In haproxy I have a real server called turnstile_verifier pointing to challenges.cloudflare.com : 443.
I have a backend called captcha_verifier pointing to this server.

What do you suggest I check next please?

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

Thank you for a detailed issue.

From looking at the code, we check the core object for `captcha_verifier` so is the backend definition at the root of the configuration and is available to all servers?

Following this `Added the haproxy modifications via the additional options that the OPN UI for haproxy add-on provides.` you would need to check how the configuration is being compiled to haproxy.

**Comment by cookiemonsteruk** [comment]
Hey, I didn't get a notification to your reply @LaurenceJJones apologies for the delay.
> is the backend definition at the root of the configuration and is available to all servers?
Yes to both questions.
> you would need to check how the configuration is being compiled to haproxy.
I have and all seems correct.
I have not made any changes since this report but the loop has not re-occurred. I _think_ it is all OK, just no idea why it occurred at the start.
Thanks for your comment. Will close in a few days if that's Ok. I want to document it before it disappears.

**Comment by cookiemonsteruk** [comment]
Closing now for tidiness.
